### ISSUE TITLE
"panic: can't load DRDOS.SYS, giving up" when trying to load dual-file SvarDOS flavour off fdb

### ISSUE THREAD

**Issue by ecm-pushbx** [SvarDOS/edrdos#100]
Start lDebug off fda in qemu, with the current release of edrdos.img as fdb. Then enter `boot protocol freedos fdb/drbio.sys` or `boot protocol edrdos fdb`. The kernel will load at first but halt with the panic.

**Comment by ecm-pushbx** [comment]
Loading off `fda` works as expected, both load protocols.

**Comment by boeckmann** [comment]
This my also be for the ordinary dual-file version. I have to check...

**Comment by boeckmann** [comment]
Should be fixed by [c4c576d](https://github.com/SvarDOS/edrdos/commit/c4c576d429937b8ce21051028658224da6ed69bf)

**Comment by boeckmann** [comment]
Interestingly this code section already existed in the original 7.01 source. So maybe OpenDOS 7.01 never was able to boot from B:? Would be interesting to test with the original distribution files :)
