### ISSUE TITLE
No COMSPEC in boot environment unless CONFIG.SYS sets anything

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/edrdos#101]
Not entirely sure this is a kernel bug, still have to debug it to understand better what happens, but here's the symptom: when booting EDR from the SvarDOS install floppy, I noticed there is no COMSPEC in the environment.

![image](https://github.com/user-attachments/assets/e59bb72e-4bd0-49fb-a699-83e997a585c9)

Now, if I only add a `SET SOMETHING=...` directive to CONFIG.SYS, then COMSPEC appears.

![image](https://github.com/user-attachments/assets/0fc6c6d2-34ca-4a1e-a6e0-e8c2705e3e32)

**Comment by mateuszviste** [comment]
Now with some config-env debug data (output by SvarCOM when it is invoked by the kernel). When it works fine:

![image](https://github.com/user-attachments/assets/a11c6d7b-40ca-42ea-8d1a-17e229a92e56)

when it does not:

![image](https://github.com/user-attachments/assets/c9ae38b1-e60f-44d7-a0e7-626fd89146ba)

So the COMSPEC variable is actually there, but the environment starts with a 0 so SvarCOM thinks it is empty.

Also, in both cases there is no "exec string" trailing the environment strings.

**Comment by boeckmann** [comment]
Thanks for the pictures. These clearly show what is going on. I have to treat the empty env as a  special case.

**Comment by boeckmann** [comment]
I hope https://github.com/SvarDOS/edrdos/commit/525b418819b1c775afd040f28c0254fb527646ae fixes it. Build is under artifacts.

**Comment by mateuszviste** [comment]
Confirmed, it works. Thank you!

![image](https://github.com/user-attachments/assets/00cc14f2-8ebd-4c77-9c3f-e0ce0f686ad0)
