### ISSUE TITLE
Should "..." be equivalent to ".." ?

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/edrdos#106]
The EDR kernel accepts "..." as a directory, but treats it apparently just like "..". This seems odd to me - I assume it's either a bug in parsing and "..." should be rejected, or it's some feature (I'd assume going back 2 directories) from the past that stopped working.

![image](https://github.com/user-attachments/assets/93f40906-bea3-45e1-9fa9-5df1e916177d)

**Comment by ecm-pushbx** [comment]
In MSW 98 you can indeed use three-dots to go up two levels. Not sure whether it is supported when the LFN server isn't loaded. Or whether doslfn supports this too.

**Comment by andrewbird** [comment]
> In MSW 98 you can indeed use three-dots to go up two levels. Not sure whether it is supported when the LFN server isn't loaded. Or whether doslfn supports this too.

Interesting, I wonder if the '...' is resolved by truename / (qualify_filename int2f/1123 in the redirector) to a normal path. If that's the case then probably the shell shouldn't do any syntax checking, and only report whether the 'cd' was successful.

**Comment by mateuszviste** [comment]
The shell here does not perform any syntax checking.

Good question about truename - I checked and no, sadly it does not understand "...", so it's probably not a dysfunctional feature, but just some EDR parsing glitch.

![image](https://github.com/user-attachments/assets/11ab4550-dcdf-43d3-be98-9c0f1f8c9c45)

**Comment by lproven** [comment]
> In MSW 98 you can indeed use three-dots to go up two levels.

Concur.

`.` is this directory; `..` is the parent; this was extended logically upwards, as far as I recall indefinitely. `...` = parent of parent, `....` parent of grandparent, `.....` grandparent of grandparent, etc.

I liked it and was surprised when moving to xNix, ~3 decades ago, that it did not do the same. But I am that very rare xNix user who _prefers_ the classic DOS or NT shell to any xNix shell.

**Comment by andrewbird** [comment]
I just tried this with freecom on FDPP/dosemu2
##### filesystem is MFS (Dosemu2's redirector)
~~~
FreeCom version 0.84-pre2 XMS_Swap [Aug 28 2006 00:29:00]
DOS version 5.0
FDPP kernel 1.7 [GIT: ] (compiled Aug  7 2024)
C:\doc\nasm\html>truename .
C:\doc\nasm\html
C:\doc\nasm\html>truename ..
C:\doc\nasm
C:\doc\nasm\html>truename ...
C:\doc
C:\doc\nasm\html>truename ....
C:\
~~~

##### switch filesystem back to FATFS
~~~
Redirection for drive C: was deleted.
C:\>cd \doc\nasm\html
C:\DOC\NASM\HTML>truename .
C:\DOC\NASM\HTML
C:\DOC\NASM\HTML>truename ..
C:\DOC\NASM
C:\DOC\NASM\HTML>truename ...
File not found. - '...'
C:\DOC\NASM\HTML>truename ....
File not found. - '....'
~~~

So it seems that Dosemu's lfn(only works on MFS) implementation of truename (int21 7160) is doing the resolving.

**Comment by ecm-pushbx** [comment]
Picked into https://hg.pushbx.org/ecm/edrdos/rev/353577d5dbca
