### ISSUE TITLE
default COMSPEC does not provide drive if SHELL directive does not mention it

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/edrdos#108]
This is similar to #101 but not exactly the same scenario.

When I have a `SHELL=COMMAND.COM` in CONFIG.SYS, the kernel appears to copy it as-is into COMSPEC, so I end up with a relative COMSPEC (as in `COMSPEC=COMMAND.COM`). Such COMSPEC will fail as soon as the user changes its default drive.

This is my config.sys:

![image](https://github.com/user-attachments/assets/cc409d72-137f-419c-9ab9-3fba883a392a)

This is the dump of the kernel environment at boot time:

![image](https://github.com/user-attachments/assets/071cae99-ff69-4432-ae7c-79397a118ed6)

And this is the result:

![image](https://github.com/user-attachments/assets/c3a05b36-f278-4608-afeb-33d332c3e4fd)

Shortly said - the kernel should put the full path to COMMAND.COM into COMSPEC (including the drive), even if the SHELL directive did not mention the drive.

**Comment by boeckmann** [comment]
Yes, should be changed.

**Comment by boeckmann** [comment]
This is hopefully fixed by db318b3

**Comment by ecm-pushbx** [comment]
> This is hopefully fixed by [db318b3](https://github.com/SvarDOS/edrdos/commit/db318b3cce2d95c52f69155bfc81a43aa0be3b89)

Picked into https://hg.pushbx.org/ecm/edrdos/rev/3e3bb89ed581

**Comment by mateuszviste** [comment]
> This is hopefully fixed by [db318b3](https://github.com/SvarDOS/edrdos/commit/db318b3cce2d95c52f69155bfc81a43aa0be3b89)

I confirm, it works now. Thanks!

![image](https://github.com/user-attachments/assets/5382c31f-2382-4fd7-b6c2-b439e4762944)
