### ISSUE TITLE
wild license.htm file in SvarDOS package

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/edrdos#119]
The github-built SVP package of the EDR kernel has a DOC/LICENSE.HTM file. Such location is invalid as it does not make it clear what package it belongs to. Should be either:

1. DOC/KERNLEDR/LICENSE.HTM
  or
2. DOC/KERNLEDR.TXT

The option 2 is probably preferable (esp. since HTM is difficult to read in DOS).

**Comment by boeckmann** [comment]
https://github.com/SvarDOS/edrdos/commit/529e535fc260b8e2ffb1d1f5f12efb735ce5d24c

Moved it to DOC/KERNLEDR. I wrote Brian Sparks with a request to clarify the license thing. Got no feedback yet (and probably never will). For the moment I think its better to leave the E-Mail conversation as in the original HTML.

**Comment by mateuszviste** [comment]
Thanks :)
