### ISSUE TITLE
Move discarded buffers to end of LRU chain

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/edrdos#121]
There are situations where the kernel discards some of its sector buffers via one of its [discard_*](https://github.com/SvarDOS/edrdos/blob/a027cb89e00acc30cddfd35509c4453f4d9f6a58/drdos/buffers.asm#L268-L291) routines, for example when it detects a disk change. The kernel discards a buffer by setting the buffers drive field to 0xFF and its dirty flag to false, without moving the buffer to the end of the least recently used chain.

However, if a buffer is aquired via [locate_buffer](https://github.com/SvarDOS/edrdos/blob/a027cb89e00acc30cddfd35509c4453f4d9f6a58/drdos/buffers.asm#L1033-L1098), it always returns the last buffer of its LRU cache, if the sector requested is not in the cache. This leads to situations where buffers still holding valid sector data are recycled while there are still discarded buffers in the cache.

This leads to sub-optimal cache usage and may lead to unneccessary IO operations.

I see two possible ways to prevent this:

1. Always move discarded buffers to the end of the LRU chain.
2. When locating a buffer for a sector not hold in the cache prefer buffers with drive set to 0xFF.

**Comment by boeckmann** [comment]
With 4246b8bc93e68c01398e8abfa74dd7b27462b988 I changed `locate_buffer` to preferably recycle discarded buffers. Beside this slight optimization the cache strategy is stupid (basically does not exist apart from LRU). However, even this change seems to reduce the number of disk changes needed when copying files between phantom drives and doing non-sector aligned IO. Btw the default numbers of buffers is five for systems with 640k conventional memory.

**Comment by ecm-pushbx** [comment]
Picked in https://hg.pushbx.org/ecm/edrdos/rev/243525ce79db
