### ISSUE TITLE
command.com: determination of executable file name broken

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/edrdos#23]
After start, command.com tries to detect its file name in case it has to reload itself or it wants to load help messages appended to the executable. This determination is initially performed by [exec_name](https://github.com/SvarDOS/edrdos/blob/71c5acaec8201f83b371fc7695ff8e3e92df9656/command/cstart.asm#L1308), loading the file name from the environment. After calling exec_name, `reload_file ` contains a valid executable file name.

However, when [init()](https://github.com/SvarDOS/edrdos/blob/71c5acaec8201f83b371fc7695ff8e3e92df9656/command/com.c#L452) runs, it calls [get_cmdname](https://github.com/SvarDOS/edrdos/blob/71c5acaec8201f83b371fc7695ff8e3e92df9656/command/csup.asm#L347C2-L347C2), which determines the executable name from the parent PSP and unconditionally sets this as new reload_file (get_cmdline always returns zero). However, this at least fails if command.com is executed as a child process. The file name is also copied from a suspicious location, namely offset 62h of the PSP, pointing to the middle of the file name of the first FCB. When trying to copy the name from this position, it basically destroys to previously valid `reload_file`.

To my understanding, and at least in all cases I tested, the call to get_cmdline can safely be removed in init(). After that, command.com behaves as expected even under DOSBOX (at least help gets shown and it can reload itself).

But perhaps @ecm-pushbx may have an idea why get_cmdline is implemented as it is. In my opinion, at least getting the file name from offset 62h makes no sense.

**Comment by boeckmann** [comment]
DOSBOX and probably MS-DOS player fail to load the help text. COMMAND.COM opens itself to read the help text that is appended to COMMAND.COM as a binary blob into memory. The absolute path for COMMAND.COM is stored in the variable `reload_file`. The path starts with a binary zero (for the default drive) instead of a drive letter (see screenshot). DR-DOS and FreeDOS Kernels support such a filename, while DOSBOX and MS-DOS player probably not. Therefore commands like `dir /?` fail.

![grafik](https://github.com/SvarDOS/edrdos/assets/6333969/63f77aa9-a8e6-46f1-b2f0-619577a48102)

**Comment by boeckmann** [comment]
To my understanding [e85d927](https://github.com/SvarDOS/edrdos/commit/e85d9275a60c26c2658785f1cc0d21d6c2773946) fixes it. If it prooves correct, `get_cmdline `can be removed alltogether, because it is not used anymore.

**Comment by ecm-pushbx** [comment]
> But perhaps @ecm-pushbx may have an idea why get_cmdline is implemented as it is. In my opinion, at least getting the file name from offset 62h makes no sense.

No idea at all, I barely have some knowledge about the kernel, less than that even on dcommand
