### ISSUE TITLE
Substitute RASM86

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/edrdos#35]
This is the only (but HUGE) dependency left which prevents building the EDR-DOS with free software and under different operating systems than DOS.

But to my knowledge, no free RASM86 compatible assembler exists yet.

**Comment by rofl0r** [comment]
nice one. there's also the wrapper exe rasm_sh which seems to do some subst trick, which caused the rasm86 command to fail in various emulators.

**Comment by boeckmann** [comment]
> there's also the wrapper exe rasm_sh which seems to do some subst trick
I had that tought too. It also passes definitions given via command line to the assembler, probably by writing them into a file. But I had not investigated that in detail.

**Comment by rofl0r** [comment]
iirc i tried to run the rasm part of make.bat in emu2, a sweet lightweight 286 emulator and it complained about subst failing. in other emulators i just get errors about an asm file not being found that's clearly there.

**Comment by ecm-pushbx** [comment]
The subst commands that the wrapper runs are intended to set up drive I: so that it points to the repo's drdos/ directory. This is why my mak.bat script for dosemu2 uses lredir to set up the same setup but as a dosemu2 machfs redirection instead: https://hg.pushbx.org/ecm/edrdos/file/6497e3a1a0c7/mak.bat#l6

The subst commands will fail with this setup, displaying an error message before and after every assembly step, but the rasm86 assembler proper will work as intended.

**Comment by roytam1** [comment]
I think we can need to port sources to, for example, jwasm.

**Comment by roytam1** [comment]
> The subst commands that the wrapper runs are intended to set up drive I:

yeah and thats why it fails to build here since I do acutally have an I: drive in use.

**Comment by boeckmann** [comment]
> I think we can need to port sources to, for example, jwasm.

Yes, in the long term I think this is the best option. But it is a lot of work...

**Comment by ecm-pushbx** [comment]
I created a script that does most of the work of converting MASM sources to NASM, could be useful here too: https://hg.pushbx.org/ecm/warplink/file/88412ae14f49/fixmem.pl

There's also NoMySo which has a similar goal: http://www.devoresoftware.com/nomyso/

**Comment by roytam1** [comment]
> I created a script that does most of the work of converting MASM sources to NASM, could be useful here too: https://hg.pushbx.org/ecm/warplink/file/88412ae14f49/fixmem.pl

if JWASM can work on MASM syntax, I don't think there is a need to convert them to nasm syntax IMHO.

**Comment by boeckmann** [comment]
DRBIO is now fully converted to JWasm.

**Comment by boeckmann** [comment]
Depends on #62
