### ISSUE TITLE
zero-compress the whole DRBIO.SYS?

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/edrdos#38]
The compressed DRBIO.SYS still contains ~10k of padding zeroes. This means DRBIO.SYS could be compressed to 26k, if zero-compressed as a whole.

This would require changes in the boot process, perhaps by an intermediate loader that gets prepended to the DRBIO.SYS, or as an extension to the volume boot code? The decompression algorithm does not take that many bytes.

**Comment by ecm-pushbx** [comment]
> or as an extension to the volume boot code? The decompression algorithm does not take that many bytes.

Absolutely not, this would require a new protocol and highly valuable space in the loader.

**Comment by boeckmann** [comment]
I think this is implicitly solved by using compressed kernel images., like the ones @ecm-pushbx provides. So this would not get us much.

**Comment by rofl0r** [comment]
does this mean that in the future you plan to ship ecm's kernel instead of this one ?

**Comment by boeckmann** [comment]
Yes, because the version in this repo does currently not support compression. But probably I will make packages for both, ECMs version and the one from this repo. The SYS command provided by SvarDOS will be able to handle both. The one here will stay in its "legacy" DRBIO.SYS, DRDOS.SYS from.
