### ISSUE TITLE
DRSYS tries to transfer an invalid-path "C:.\COMMAND.COM" file

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/edrdos#43]
Seen on a virtualbox VM running SvarDOS:

![image](https://github.com/SvarDOS/edrdos/assets/9503501/d52447f0-e95f-4e3b-b015-b4499aad5024)

Apparently DRSYS first tries to open a (hardcoded?) "C:.\COMMAND.COM file, fails to do so and only then falls back to %COMSPEC%.

**Comment by ecm-pushbx** [comment]
DRSYS is just a patched version of FreeDOS SYS. (Not sure how recent it is.) Therefore we can look at FreeDOS SYS's sources: https://github.com/FDOS/kernel/blob/8552d833bbca657591fa8e6f7276d307d7d0c7c6/sys/sys.c#L833

**Comment by boeckmann** [comment]
> DRSYS is just a patched version of FreeDOS SYS.

Correct, it is compiled from commit https://github.com/FDOS/kernel/commit/db949bf0b264072147a79211192c2ceac62a08a7, which includes some of @ecm-pushbx changes to the boot loaders, specifically https://github.com/FDOS/kernel/commit/42d3ae6aacf4dbc948220b813ab29fffdb5d0803 dealing with EDR compatibility. It is compiled with DRDOS defined to make this the preferred kernel when DRSYS is run.

**Comment by boeckmann** [comment]
@mateuszviste can this be considered to be obsolete?

**Comment by mateuszviste** [comment]
I think so, yes. The current SYS works well for me and I did not notice any obvious issues.
