### ISSUE TITLE
CHCP fails with error 26112

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/edrdos#45]
Tested with SvarCOM:

![image](https://github.com/SvarDOS/edrdos/assets/9503501/58aee3c7-4381-493f-b76e-a73e47c9766a)

Not sure what the error number 26112 is supposed to be.
SvarCOM's CHCP works fine with both MSDOS and FreeDOS kernels.

The exact code that is executed is this:

![image](https://github.com/SvarDOS/edrdos/assets/9503501/14d0a38d-e865-43ea-88ae-cda67805cf29)
(full source [here](http://svn.svardos.org/filedetails.php?repname=SvarDOS&path=%2Fsvarcom%2Ftrunk%2Fcmd%2Fchcp.c))

**Comment by boeckmann** [comment]
Thanks for the report. I will have a look at this.

**Comment by mateuszviste** [comment]
on a related note:

![image](https://github.com/SvarDOS/edrdos/assets/9503501/a2c98569-0b41-4960-8f43-82f4f6466954)

I do not know if this is on purpose or not... Is EDR-DOS supposed to provide the INT 0x2F NLSFUNC interface out of the box?

SvarCOM's code that checks for NLSFUNC presence is this:

![image](https://github.com/SvarDOS/edrdos/assets/9503501/e57234b1-5ff2-4796-9f28-795a8240e81e)

ref. http://www.techhelpmanual.com/693-int_2fh_1400h__is_nlsfunc_exe_installed_.html

**Comment by boeckmann** [comment]
> I do not know if this is on purpose or not... Is EDR-DOS supposed to provide the INT 0x2F NLSFUNC interface out of the box?

No, EDR depends on an external NLSFUNC. Only for parsing and processing config.sys including the COUNTRY= line, temporary built-in INT2F,14 support is installedl. But it is dumped after kernel initialization.

**Comment by mateuszviste** [comment]
> No, EDR depends on an external NLSFUNC. Only for parsing and processing config.sys including the COUNTRY= line, temporary built-in INT2F,14 support is installedl. But it is dumped after kernel initialization.

I'm a little bit confused because still, the kernel handles INT 21h/AX=65xxh calls (at least AX=6506h for sure)... Aren't these also supposed to be NLSFUNC?

Or maybe - the NLSFUNC API is present, but *checking* for it is not supported due to a missing INT 2Fh handler?

**Comment by boeckmann** [comment]
If it is queries for the current country / code page then the info stored in memory is reported back by the kernel. If it is about a country / code page currently not loaded the kernel calls INT2F, so NLSFUNC must be installed.

So NLSFUNC is needed only if you want to change country / code page after the system is booted, if I understand all this spaghetti code correctly. But I will have a second look...
