### ISSUE TITLE
Setup automatic builds via Github action

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/edrdos#47]

**Comment by andrewbird** [comment]
This commit may help get you underway https://github.com/FDOS/kernel/pull/137/commits/085d2c9d7944255255b8f92a88b7218c49889931#diff-117d0eacf4a2a5b7c70bd4e28ef06312fa6945d7330eb01c7255a21d1ddd205a for WatcomC at least.

**Comment by rofl0r** [comment]
fwiw, rasm86 also runs under the tiny [emu2](https://github.com/dmsc/emu2/), which is a loooooooooot less of a pain to get compiled from source than dosemu(2). in fact, it only requires a C compiler and about 15 seconds single-core cpu time, while dosemu2 has dozens of dependencies and a source tree at least 1000x as big. the rest of the toolchain doesn't run there though, as emu2 only emulates x86 upto 286. in my tests using it, i just made MAKE.BAT jump directly to the rasm commands.

**Comment by boeckmann** [comment]
@rofl0r that sounds very promising. In fact RASM86 is the only program of the build tools that only runs under dos. Everything else runs under Windows / Linux. FIXUPP, COMPBIOS and COMPBDOS are replaced by open source re-implementations. And linking is done with Watcom WLINK.

**Comment by roytam1** [comment]
> In fact RASM86 is the only program of the build tools that only runs under dos

rasm86 can work under ntvdm.

**Comment by boeckmann** [comment]
I will do this after the kernel is fully ported to JWasm. Then it can be built natively under Linux.

**Comment by boeckmann** [comment]
Depends on #62
