### ISSUE TITLE
Implement INT21,440D,47/67 get/set access flag and make use of it

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/edrdos#49]
These methods should set/unset bit 9 of UDSC_FLAGS.

The flag should be used to deny read / write / verify disk io if flag is set.

This in a second step could be used to block acces to uninitialized FAT partitions. Like it is implemented now, it is a lottery game if access succeedes even if the partition is uninitialized (valid BPBs are generated for all partitions). Success then depends on the FAT area by accident containing "valid" data.

**Comment by boeckmann** [comment]
initial implementation by https://github.com/SvarDOS/edrdos/commit/a74e21180e272a127d5b37d8639a75a7de2a383d and [4dbe134](https://github.com/SvarDOS/edrdos/commit/4dbe13473d65b579e4c2cea4f5ca2016aed6567d)

**Comment by ecm-pushbx** [comment]
The `xor`  confuses me, can you explain? https://github.com/SvarDOS/edrdos/commit/a74e21180e272a127d5b37d8639a75a7de2a383d#diff-77a7937e0b578117d8157fb359a1672c8c120ffd0cd9d76a904110f8d5cd7f62R2059

**Comment by boeckmann** [comment]
> Besides, you have some lines like `cmp ds:1[bx],byte ptr 0` where you put the size on the immediate operand rather than the memory operand. This is valid but I'm unsure if my scripting can deal with it. If there is no reason to prefer that I'd suggest avoiding these in the future.

Ok, I will avoid it.

**Comment by boeckmann** [comment]
> > The `xor` confuses me, can you explain? [a74e211#diff-77a7937e0b578117d8157fb359a1672c8c120ffd0cd9d76a904110f8d5cd7f62R2059](https://github.com/SvarDOS/edrdos/commit/a74e21180e272a127d5b37d8639a75a7de2a383d#diff-77a7937e0b578117d8157fb359a1672c8c120ffd0cd9d76a904110f8d5cd7f62R2059)
> 
> It is basically the same as `AND ax, NOT UDF_NOACCESS`, so clears the UDF_NOACCESS flag.

But I can rewrite it as AND, because it is indeed confusing as this could change it to 1 actually...
