### ISSUE TITLE
find out how COMPBIOS works

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/edrdos#5]

**Comment by ecm-pushbx** [comment]
As I mentioned in https://github.com/SvarDOS/edrdos/issues/7#issuecomment-1877851434 the depacking happens all in https://hg.pushbx.org/ecm/edrdos/file/465be5fcbb65/drbio/init.asm#l751

**Comment by boeckmann** [comment]
I added some remarks to COMPBIOS.C.
