### ISSUE TITLE
lDebug question

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/edrdos#50]
EDIT: Figured it out by myself already. One can set the carry flag via R CF=1 :)

The original question whould have been:

I was able to load and boot the EDR kernel via lDebug by
```
boot protocol=edrdos fda
```
from floppy drive. The EDR kernel contains a check to not rewrite INT 3 vector when running under a debugger:
https://github.com/SvarDOS/edrdos/blob/386a0dd0af3cf1d8aecfcf4feaffaca4ed57cd74/drbio/init.asm#L848-L850

I do not know how to set the carry flag from lDebug. There are flag variables [1], but they are documented to be read-only.

What I want to achieve: I added a INT 3 instruction to the kernel at a place I want to debug. I want lDebug to catch this INT 3, so I can start debugging right from the intended place. @ecm-pushbx I could need some advice how to achieve this with lDebug. Thanks :-)

[1] https://pushbx.org/ecm/doc/ldebug.htm#varfldot

**Comment by ecm-pushbx** [comment]
`r cf = 1` works. So does `r f CY` or `r fl or= 1`

**Comment by ecm-pushbx** [comment]
When the `jc` is displayed you can also use `t=taken`
