### ISSUE TITLE
compbios and compbdos port to ia16 gcc / libi86

### ISSUE THREAD

**Issue by ecm-pushbx** [SvarDOS/edrdos#54]
As mentioned in https://github.com/SvarDOS/edrdos/issues/53

This is the main patch: https://hg.pushbx.org/ecm/edrdos/rev/15f49e42bfae

And here's a patch I missed at first, the casts have to be specified as far too: https://hg.pushbx.org/ecm/edrdos/rev/3f83aad9522a

**Comment by ecm-pushbx** [comment]
(Do correct me if I need to update my toolchain.)

**Comment by boeckmann** [comment]
I noticed there are some implementation-specific x86 __far pointer attributes in the source. I'd like the sources for COMPBIOS and COMPDOS to be compilable under other OSes than DOS / Windows, and therefore for the moment decided against importing these changes.

**Comment by ecm-pushbx** [comment]
I could prepare a patch that uses defines for the far keywords and functions, so that they could be used when compiling for 16-bit DOS and omitted / fall back to non-far otherwise. Sound good?

**Comment by boeckmann** [comment]
> I could prepare a patch that uses defines for the far keywords and functions, so that they could be used when compiling for 16-bit DOS and omitted / fall back to non-far otherwise. Sound good?

Sounds good :)

**Comment by ecm-pushbx** [comment]
I forgot about this for a while. Here's the patch: https://hg.pushbx.org/ecm/edrdos/rev/729bae2f79d7 Or if you prefer one patch for all the changes to the tools, use `hg d ltools/ -r e856dafe8fa2` which I wrote to http://pushbx.org/ecm/test/20240510.dif

In this revision, I'm dispatching based on whether `__FAR` is defined.

**Comment by boeckmann** [comment]
Tanks! Compiles beautifully under Watcom :) I simply copied over the files from your tip and let Git do the rest. 58e26d4fa56b077978b5351753e3d42a5ec78566
