### ISSUE TITLE
Can RASM86 generate listing files?

### ISSUE THREAD

**Issue by ecm-pushbx** [SvarDOS/edrdos#61]
It would be of use to me to have listing files from RASM86 so as to write a script that converts the individual listing files to the trace listing understood by lDebug's TracList. I [did similar work on scripts](https://hg.pushbx.org/ecm/tractest/shortlog/8bc90e412637) for MSDebug (ancient MASM), Debug/X (patched JWasm), and the lDOS fork of MS-DOS v4 (MASM).

Prompted by the difficulty of keeping track of corresponding sources while tracing around to figure out the problem in https://github.com/SvarDOS/edrdos/issues/60

**Comment by boeckmann** [comment]
RASM86 by itself should be capable of doing it. This is from the RASM86 manual:
![grafik](https://github.com/SvarDOS/edrdos/assets/6333969/01e133ed-1cfd-4c0a-93d5-ec729522200b)

As a test I changed the following line of the DRBIO makefile
```
RASM_FLAGS = $$szpz /DDRDOS35=0 /DADDDRV=0
```
to
```
RASM_FLAGS = $$szpd /DDRDOS35=0 /DADDDRV=0
```
This puts the listing file onto what RASM86 thinks is drive D:. This happens to be the same drive as for the generated object file. It was previously output to "z", indicating the NUL device.

@ecm-pushbx, if you want the whole manual I may send you the PDF.

PS: Having the RASM_SH.EXE shim as a binary blob does not make me happy.

**Comment by boeckmann** [comment]
I am not sure if the shim blackbox always maps to drive D:, or if it is because the files are on my D: drive. So if it does not work you, try substituting d with your actual drive.

**Comment by ecm-pushbx** [comment]
Yeah, `pd` saves to drive D: regardless. So that's a hurdle. Worse: The relocations are marked by an `R` (internal relocation) or `E` (external relocation) but the exact bytes participating in the relocation aren't marked in any way it seems. So that will require significant guess work to get a complete trace listing file.

**Comment by ecm-pushbx** [comment]
At least the `<name> dseg` and `<name> cseg` directives seem straightforward. And the listing offsets seem to be what I want. If you have any idea about the relocations do tell!

**Comment by ecm-pushbx** [comment]
> @ecm-pushbx, if you want the whole manual I may send you the PDF.

Cannot do any harm I guess, do send it!

**Comment by ecm-pushbx** [comment]
Ah, passing only `$sz` the assembler will generate a listing file on the current drive (or same as the source?) and rasm_sh.exe will move the listing file into the bin subdirectory same as it does for the .o86 file.

**Comment by ecm-pushbx** [comment]
The .sym file is not much help.

**Comment by ecm-pushbx** [comment]
I'm looking at [your fixupp sources](https://hg.pushbx.org/ecm/edrdos/file/dde66e015fb8/ltools/fixupp.c), do you think I could tickle the object files to receive the exact offsets of relocations in each section? I have very little knowledge of the o86 or OMF object formats so far.

**Comment by boeckmann** [comment]
> I'm looking at [your fixupp sources](https://hg.pushbx.org/ecm/edrdos/file/dde66e015fb8/ltools/fixupp.c), do you think I could tickle the object files to receive the exact offsets of relocations in each section? I have very little knowledge of the o86 or OMF object formats so far.

You could read out the offsets of the fixup targets regarding the beginning of the segments as defined in the .OBJ files. But I doubt that this is of much use, because these logical segments (or sections, in NASM vocabulary) normally get combined at the linking stage (for examble DATA segment of A.OBJ and B.OBJ), and the fixupps are altered accordingly by the linker.

If you want to gain some insights into the OMF files I'd rather recommend to use my bug fixed fork of the NASM OMFDUMP.C instead of the FIXUP.C. OMFDUMP shows a human readable decoding of the fixupp records (this is where the NASM version fails) https://github.com/boeckmann/omfdump.

I will try to understand what exactly is needed to make the TracList work, as I have not used it yet. Seems it is used to do a sort of symbolic debugging (if thats the right term in this case) by mapping code (and data?) addresses to source lines? I will have a look at https://hg.pushbx.org/ecm/tractest/file/tip/doc after I got the doc compiled...

**Comment by ecm-pushbx** [comment]
> > I'm looking at [your fixupp sources](https://hg.pushbx.org/ecm/edrdos/file/dde66e015fb8/ltools/fixupp.c), do you think I could tickle the object files to receive the exact offsets of relocations in each section? I have very little knowledge of the o86 or OMF object formats so far.
> 
> You could read out the offsets of the fixup targets regarding the beginning of the segments as defined in the .OBJ files. But I doubt that this is of much use, because these logical segments (or sections, in NASM vocabulary) normally get combined at the linking stage (for examble DATA segment of A.OBJ and B.OBJ), and the fixupps are altered accordingly by the linker.

No, this is exactly what I need. It isn't well documented but the scripts like [convmasm.pl](https://hg.pushbx.org/ecm/tractest/file/8bc90e412637/convmasm.pl) accept a map file and listing files. They need the offsets of the fixup targets within the listing file's part of a section. They use this to mark the relevant stretches of bytes as relocatable (surround them by square brackets in the machine code dump). Later, the offset is fixed up from the per-object offset in the .lst files to the per-segment offset in the final executable, so as to match the IP value at which an instruction is executed.

> If you want to gain some insights into the OMF files I'd rather recommend to use my bug fixed fork of the NASM OMFDUMP.C instead of the FIXUP.C. OMFDUMP shows a human readable decoding of the fixupp records (this is where the NASM version fails) https://github.com/boeckmann/omfdump

Thanks. I've already started extending fixupp but this is likely to be easier to use.

> I will try to understand what exactly is needed to make the TracList work, as I have not used it yet. Seems it is used to do a sort of symbolic debugging (if thats the right term in this case) by mapping code (and data?) addresses to source lines? I will have a look at https://hg.pushbx.org/ecm/tractest/file/tip/doc after I got the doc compiled...

The trace listing format expected by traclist.pl's `--listing` switch is based on the NASM listing file output for `-f bin` format output. The offsets listed in the listing file are considered along with the dumped machine code bytes and [a selection of start offsets](https://pushbx.org/ecm/doc/traclist.htm#options-offset) (default are 0, 256, and 7C00h) to map the currently disassembled bytes (along with the (E)IP) to a line in the trace listing. Relocated bytes marked by square brackets are matched as wildcards rather than exactly.

The point of TracList is to couple it with the (serial terminal) output of lDebug. You need another window/screen/terminal to run both concurrently. Whenever the debugger disassembles something, it is emitted by tractest (the C program) into the line file and then TracList will try to jump to the corresponding line in the trace listing file.

**Comment by boeckmann** [comment]
Ok now I understand better.

A few hints if you really want to fiddle around with the OMF: The relevant parts are the LEDATA and FIXUPP records. The LEDATA records contain bytes of a section. RASM86 seems to restrict their size to 128 byte. Part of the LEDATA is an offset into the section the bytes are to be placed (as the segments are normally made of more than one LEDATA record). The FIXUP records contain an offset into the preceeding LEDATA record. So if you want to calculate the segment-relative address for a fixup, you have do add the LEDATA offset to the FIXUPP offset. The type of the fixup indicates the size of the relocation (most of the time 16 bits, but may be 32 bits for far pointers, though some compilers split that into two 16 bit segment, offset relocations).

You may iterate over the OMF records to generate a list containing lines with segment name, offset, fixupp size from it. That should be sufficient to match it to the source and surround the required parts by [].

**Comment by boeckmann** [comment]
Example:
```
a0 LEDATA16    126 bytes, checksum 56 (valid)
                segment 'INITCODE', offset 0172
   0000: 73 38 a1 00 00 e8 50 00-72 30 8e 06 00 00 26 a1  :  s8....P.r0....&.
   0010: 00 00 f7 d0 8e 06 eb 06-26 a3 00 00 a1 eb 06 e8  :  ........&.......
   0020: 36 00 72 16 33 f6 33 ff-b9 00 01 8e 06 00 00 8e  :  6.r.3.3.........
   0030: 1e eb 06 f3 a7 0e 1f 74-01 f9 c3 0e 07 bb c0 06  :  .......t........
   0040: 26 88 57 01 2e ff 1e 1b-02 2e ff 1e 1f 02 26 f7  :  &.W...........&.
   0050: 47 03 00 02 74 01 f9 c3-c4 1e ef 06 26 c7 07 ff  :  G...t.......&...
   0060: ff 0e 07 bb cd 06 26 88-57 01 26 c7 47 0e 00 00  :  ......&.W.&.G...
   0070: 26 89 47 10 26 c7 47 12-01 00                    :  &.G.&.G...
9c FIXUPP16     45 bytes, checksum 7A (valid)
   FIXUP  segment-relative, type 1 (16-bit offset)
          record offset 0003
          frame method F5 (TARGET index)
          target method T6 (EXTDEF) index 0028 'MEM_CURRENT'
   0000: c4 03 56 28 c4 0c 56 28-c4 16 54 01 c4 1d 54 01  :  ..V(
   FIXUP  segment-relative, type 1 (16-bit offset)
          record offset 000c
          frame method F5 (TARGET index)
          target method T6 (EXTDEF) index 0028 'MEM_CURRENT'
   0004: c4 0c 56 28 c4 16 54 01-c4 1d 54 01 c4 2d 56 28  :  ..V(
   FIXUP  segment-relative, type 1 (16-bit offset)
          record offset 0016
          frame method F5 (TARGET index)
          target method T4 (SEGDEF) index 0001 'INITDATA'
```
This is the listing:
```
 0172 7338           01AC          jnc    BMCheck10               ; yes, skip the checks
 0174 A10000       E              mov     ax,mem_current          ; read into low memory
 0177 E85000         01CA         call    BusMasterRead           ; read one sector from disk
 017A 7230           01AC          jc     BMCheck10               ; give up if we couldn't read

 017C 8E060000     E              mov     es,mem_current          ; ensure at least the 1st word will
 0180 26A10000                    mov     ax,es:.0                ;  differ if the read doesn't happen
 0184 F7D0                        not     ax
 0186 8E06EB06     R              mov     es,UpperMemoryBuffer
 018A 26A30000                    mov     es:.0,ax
```
LEDATA starts at offset 0x126 of the INITDATA section. First relocation at offset 3 of the LEDATA, this corresponds to offset 0x175. In the listing, it is the external reference to mem_current. There is also a relocation regarding the segment-relative offset of UpperMemoryBuffer, at section offset 0x188 (or LEDATA offset 16).

**Comment by boeckmann** [comment]
As an alternative, if it is only for code I think you could also search for E and R relocation indicators in the listing and, depending on the opcode, determine the type of relocation to find out what part of the line is the relocation. But I doubt that this would be easier than adapting OMFDUMP.

This would also not work for relocations inside data definitions, I guess.

**Comment by ecm-pushbx** [comment]
> As an alternative, if it is only for code I think you could also search for E and R relocation indicators in the listing and, depending on the opcode, determine the type of relocation to find out what part of the line is the relocation. But I doubt that this would be easier than adapting OMFDUMP.

I already adapted fixupp to get me most of the way there, in https://hg.pushbx.org/ecm/edrdos/rev/a9f032337060 But thanks for the clarifications.

> This would also not work for relocations inside data definitions, I guess.

Not a priority, trace listings primarily should be for code.

**Comment by ecm-pushbx** [comment]
I'm using http://www.azillionmonkeys.com/qed/Omfg.pdf to reference the meaning of the OMF structures btw.

**Comment by ecm-pushbx** [comment]
Some more revisions up to https://hg.pushbx.org/ecm/edrdos/rev/d90416f78718

Now a third parameter can be "VERBOSE" or "RELOC" to enable additional output. The RELOC output looks like `segment="BDOS_CODE" offset=01D5h length=2` (from buffers.o86).

**Comment by boeckmann** [comment]
I mainly use these, with the latter one to understand "where it's coming from":
https://bitsavers.org/pdf/ibm/pc/os2/OS2_OMF_and_LX_Object_Formats_Revision_8_199406.pdf
http://www.bitsavers.org/components/intel/8086/121748-001_8086_Relocatable_Object_Module_Formats_1981.pdf

I also have the TIS version 1.2, but I find the OS2 reference better to  understand.

**Comment by boeckmann** [comment]
> Some more revisions up to https://hg.pushbx.org/ecm/edrdos/rev/d90416f78718
> 
> Now a third parameter can be "VERBOSE" or "RELOC" to enable additional output. The RELOC output looks like `segment="BDOS_CODE" offset=01D5h length=2` (from buffers.o86).

Great, I will do the usual re-import when you are finished with it :)

**Comment by ecm-pushbx** [comment]
The fixupp patches are done as far as I'm concerned. I [use the .rel files](https://hg.pushbx.org/ecm/tractest/rev/d710dd5a9652) for a trace listing conversion script now. (The script isn't done yet, still missing JWasm support with my or Japheth's patch for displaying relocations. But its support for RASM-86 and the fixupp RELOC files is done.)

**Comment by ecm-pushbx** [comment]
I forgot uploading some patches to my EDR-DOS repo. Done now. However, I'm looking into using .rel files for JWasm as well and trying it out on drbio/bin/init.obj causes this error to display: https://hg.pushbx.org/ecm/edrdos/file/e7889d4861e9/ltools/fixupp.c#l195

So I may add yet more revisions of fixupp.

**Comment by ecm-pushbx** [comment]
Added minimal support for absolute segments: https://hg.pushbx.org/ecm/edrdos/rev/321023f31e03
