### ISSUE TITLE
port DRDOS.SYS sources to JWasm

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/edrdos#62]

**Comment by boeckmann** [comment]
The source is ported. There are some include files with a w as the last character, like pspw.equ. These are the JWasm versions of the files without the trailing w. Now that the RASM dependency is gone, these files can be copied over to the files without w, and the files with trailing w can be removed, after all references to them were changed.

**Comment by ecm-pushbx** [comment]
I've seen a few spots where you inserted a nop with a note to drop it later. May I take it you're identicalising the JWasm replacements to generate almost exactly the same binaries as were created by RASM?

**Comment by boeckmann** [comment]
It is because JWasm generates more efficient (size wise) instructions than RASM at some places. I inserted the NOPs to make binary comparison easier. The problem is, if the code differs in size, so will the label addresses. And this will result in a huge binary difference, making comparison really hard.

On the other side, using the more efficient encodings is desireable, so I flagged all the NOPs with a comment, so that they can eventually be removed.

Basically I followed this procedure:
- Convert the source to JWasm
- compare the listing output of JWasm and RASM (I did this manually, having a tool for it would propably better)
- where the listings differ (and there are plenty of places because of differing instruction encodings), check if they have the same semantics and make sure the offsets stay the same
- build the binary
- compare the binary with the previous one to make sure that, apart from the differences in the listings, the relocations got not altered between the files because of segment mismatches etc or segment sizes changed

Doing much of it manually comes with the chance of human error. Time will tell if something slipped through...

**Comment by ecm-pushbx** [comment]
Yes, this is what I call identicalising.

**Comment by boeckmann** [comment]
I will probably write down what where the pitfalls are when converting the source from RASM to JWasm. There were a few traps. Like the / operator doing a signed division on JWasm and JWasm doing 32-bit arithmetic instead of the 16-bit arithmetic RASM does, different semantics of the length operator etc... These things are sometimes only noticeable in the resulting code generated.

**Comment by ecm-pushbx** [comment]
I [wrote about the DRBIO port](https://pushbx.org/ecm/dokuwiki/blog/pushbx/2024/0714_early_mid_july_work), also [mentioned on the forum](https://www.bttr-software.de/forum/forum_entry.php?id=21974 ). DRDOS will largely be more of the same.
