### ISSUE TITLE
RASM porting file: mov ax, 1 cannot be encoded with a sign-extended immediate

### ISSUE THREAD

**Issue by ecm-pushbx** [SvarDOS/edrdos#68]
Your example here is wrong, as `mov ax, 1` can only be encoded two ways: The normal way (B8 01 00) or the `mov modrm ax, 1` way (C7 C0 01 00). No assemblers will normally generate the ModR/M choice though. There is no imms8 encoding that uses a sign-extended byte immediate.

https://github.com/SvarDOS/edrdos/blob/2fb080ed07778354d2a32c48179932422ab5a9cf/doc/rasmporting.md?plain=1#L29

**Comment by boeckmann** [comment]
Thanks! Changed to ADD and augmented with the actual encodings.
