### ISSUE TITLE
re-implement COMPBIOS

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/edrdos#7]

**Comment by ecm-pushbx** [comment]
I simply dropped the compression done by compbios in my 2023 December update: https://hg.pushbx.org/ecm/edrdos/rev/0cf29efb060b

If you want, you can see in the conditional code in drbio/init.asm what output format is expected if this compression is used.

(I will write more about my update to single-file kernels later, probably this Sunday.)

**Comment by boeckmann** [comment]
That sounds promising. Looking forward to read more about it. I saw a LZIP call in your changes. So I guess the zero-filled areas simply get compressed by it, so that the COMPBIOS is unnecessary.

I had a first look at the compression algorithm a few weeks ago. It is relatively simple. Basically run length encoding of actual data and zeros. If I find some time I will write it down here.

**Comment by boeckmann** [comment]
Implemented as of [2bbe217](https://github.com/SvarDOS/edrdos/commit/2bbe2177a23a24d42766f3509c297f61cae57400).

When comparing the binary compressed by the original compressor with the one compressed by the re-implementation, the latter DRBIOS.SYS is two bytes smaller. The difference is that the original compressor adds four zero-bytes instead of two at the end of the file. But only two zeroes are needed to indicate the end of the compressed data. This is at least how I interpret the decompression algorithm at https://github.com/SvarDOS/edrdos/blob/2bbe2177a23a24d42766f3509c297f61cae57400/drbio/init.asm#L758-L760

I think that this is unintended behaviour of the original implementation. The DRBIO.SYS compressed with my implementation seems to work fine.
