### ISSUE TITLE
kernel fails to boot if DRDOS is uncompressed

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/edrdos#70]

**Comment by ecm-pushbx** [comment]
Did you use [my compbdos with `uncompressed` keyword](https://github.com/SvarDOS/edrdos/issues/53#issuecomment-2231871076) or the replacement scriptlet to prepare the uncompressed drdos.sys ?

**Comment by boeckmann** [comment]
Nope, with my faulty equivalent 🤦 
I forgot not to set the compressed flag...

**Comment by boeckmann** [comment]
Working now with the fixed compbdos [0c7dc2c](https://github.com/SvarDOS/edrdos/commit/0c7dc2cad65de4346e88ce7b3c97891277906da3)
