### ISSUE TITLE
Adapt FreeDOS load protocol

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/edrdos#72]
Adapting the FreeDOS load protocol would make the EDR single-file kernel a drop-in for the FreeDOS kernel. Installation would merely mean changeing the binaries.

**Comment by boeckmann** [comment]
I started working on this. Good news: kernel boots when loaded to segment 60h as kernel.sys with the FreeDOS protocol and seems to run after applying https://github.com/SvarDOS/edrdos/commit/0300461295f8b5fd5182d2f36a0390a4b36049b1. I still have to make sure the kernel correctly collects all the info the loader provides us (drive in correct register for example).

However, the output of the MEM /d /p command is a little bit strange.
<img width="576" alt="Bildschirmfoto 2024-07-24 um 19 24 33" src="https://github.com/user-attachments/assets/aebb7698-6d02-47e9-bc78-765e8ef879f6">

With the dual-file kernel it is shown like this:
<img width="563" alt="Bildschirmfoto 2024-07-24 um 19 15 07" src="https://github.com/user-attachments/assets/bd7d031f-6971-4cd4-9c1a-40b9aca4a885">

This does not have to be a problem of the kernel, but may also has something todo with MEM itself. But should be investigated...

**Comment by boeckmann** [comment]
The following line in the MEM source seem to unconditionally account 300h bytes for the BDA, shifting the BIO to 700h:

https://github.com/FDOS/mem/blob/2b2c83328d9301aa0e484e909f252e32def6c2c7/source/mem.c#L1808

This could be the cause, "shifting" the device drivers out of the assumed BIO.

**Comment by boeckmann** [comment]
> The following line in the MEM source seem to unconditionally account 300h bytes for the BDA, shifting the BIO to 700h:
> 
> https://github.com/FDOS/mem/blob/2b2c83328d9301aa0e484e909f252e32def6c2c7/source/mem.c#L1808
> 
> This could be the cause, "shifting" the device drivers out of the assumed BIO.

Yes, indeed that is the reason. A modified MEM command with the BDA taking 200h bytes displays the following:
<img width="572" alt="Bildschirmfoto 2024-07-24 um 20 32 00" src="https://github.com/user-attachments/assets/8eead3a7-cd33-47dc-b08f-9db5dd90f96b">

**Comment by ecm-pushbx** [comment]
I don't think you have to relocate the entire DOSENTRY section (my terminology) just to support loading at a different address. Multi-segment relocation that can copy forwards or backwards fits in about 128 Bytes of discardable init memory.

**Comment by boeckmann** [comment]
> I don't think you have to relocate the entire DOSENTRY section (my terminology) just to support loading at a different address. Multi-segment relocation that can copy forwards or backwards fits in about 128 Bytes of discardable init memory.

Not sure if I understand you correctly. You mean let the kernel load to 60h but then let it relocate itself back to 70h?

**Comment by ecm-pushbx** [comment]
> > I don't think you have to relocate the entire DOSENTRY section (my terminology) just to support loading at a different address. Multi-segment relocation that can copy forwards or backwards fits in about 128 Bytes of discardable init memory.
> 
> Not sure if I understand you correctly. You mean let the kernel load to 60h but then let it relocate itself back to 70h?

Yes, exactly. The fdkernpl and its descendant drkernpl do this exactly, as it is valid for the initial loader (iniload/drload), inicomp stage, or checkpl stage to load the next stage at any segment boundary between 60h and the top of usable memory (below the stack).

**Comment by boeckmann** [comment]
I reworked this, so that the kernel lives at 70h again. The zero-compressed kernel now relocates to 70h on uncompression implicitly. This means that the uncompressed single-file kernel lacks this ability. But that is a tradeoff I am ok to live with.

**Comment by boeckmann** [comment]
Follow-up issue is #76
