### ISSUE TITLE
Strip unneeded parts from kernel

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/edrdos#73]
There are some places where binary size could be reduced by stripping unneeded parts of the kernel. One obvious is stripping the ability to load a DRDOS.SYS from the single-file kernel.

**Comment by ecm-pushbx** [comment]
> There are some places where binary size could be reduced by stripping unneeded parts of the kernel. One obvious is stripping the ability to load a DRDOS.SYS from the single-file kernel.

Yes, my single-file kernel already stripped most of the BDOS loader.

**Comment by boeckmann** [comment]
@ecm-pushbx Guess where I got that from :)

**Comment by boeckmann** [comment]
BDOS loader is now stripped from the single-file kernel.
