### ISSUE TITLE
re-implement COMPBDOS

### ISSUE THREAD

**Issue by boeckmann** [SvarDOS/edrdos#8]

**Comment by boeckmann** [comment]
complete as of 9a5db03.

**Comment by boeckmann** [comment]
Perhaps because the memory otherwise could contain garbage in the unused part of the last 128 byte block, encoding to a longer sequence than if it was filled with zero? For the last of your sentence I make a new issue to investigate.

**Comment by boeckmann** [comment]
The last zero-encoded bytes of DRDOS.SYS with the original COMPBDOS and ROUND are 0x26 zeroes. With my new tool its 0x1e zeroes. So if the last 0x26-0x1e bytes, instead of zero are garbage, the file will become larger.

**Comment by ecm-pushbx** [comment]
> > (By the way, round probably should be used when building country.sys.)
>
> For the last of your sentence I make a new issue to investigate.

Links:

https://github.com/SvarDOS/edrdos/issues/37

https://github.com/SvarDOS/edrdos/issues/36
