### ISSUE TITLE
Drive letters between FreeFDISK and the EDR kernel are inconsistent

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/edrdos#80]
This is a subject that popped out in some discussions some time ago already, just confirming the issue here.

I have used FreeFDISK to partition a disk into two partitions as follows:

![svar001](https://github.com/user-attachments/assets/71bde9da-9073-4bef-be92-b8ee0a659f6f)

Then I rebooted and wanted to format the first partition -- but ultimately, I ended up formatting the second partition instead. 

![svar002](https://github.com/user-attachments/assets/6aae9e9b-b6ed-410a-81b7-7543a3f3781e)

This might obviously confuse users and could lead to loose of data despite user's best intentions.

**Comment by mateuszviste** [comment]
closely related to #59

**Comment by boeckmann** [comment]
I could change Free FDISK so it tries to match the EDR kernel drive letter assignment if DR-DOS is detected.

**Comment by mateuszviste** [comment]
> I could change Free FDISK so it tries to match the EDR kernel drive letter assignment if DR-DOS is detected.

I was thinking about a special FDISK build for EDR, but if this could be detected automatically then indeed that would be even better.

**Comment by boeckmann** [comment]
This is fixed by FDISK 1.3.16.
