### ISSUE TITLE
kernel looks for COMMAND.COM and CONFIG.SYS in C: even when it boots from D:

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/edrdos#81]
The partition scheme is this:

![svar-001](https://github.com/user-attachments/assets/1b7a22f9-d8f5-421e-8545-c01c73e1ffa2)

The drive letters displayed by FDISK are mixed up, but that's already reported under #80.

Drive D: (displayed by FDISK as C:) is the active one and it is bootable (ie. has the EDR kernel on it + SvarCOM + a proper bootcode in its VBR inserted by SYS).
When booting, EDR fails to load COMMAND.COM and asks for a path. When instructed to look for D:\COMMAND.COM it boots all right, albeit the prompt lands in C:\.

![scan-0000](https://github.com/user-attachments/assets/ec7f44aa-c21e-4b5d-825a-f57d1b050889)

I like that EDR assigns letters sequentially regardless of the partition's ACTIVE flag, but I would expect the kernel to know it boots from D: and load COMMAND.COM accordingly (and set the current directory to D:\).

**Comment by boeckmann** [comment]
> I like that EDR assigns letters sequentially regardless of the partition's ACTIVE flag, but I would expect the kernel to know it boots from D: and load COMMAND.COM accordingly (and set the current directory to D:).

I think I have messed this up in the single-file kernel, because it does not make use of the partition offset it gets from the boot loader. If you are right at it, may you test this with the dual-file version also? It this works I know how to fix it.

The general drive letter ordering sadly would be a bigger task...

**Comment by boeckmann** [comment]
This relates to https://github.com/SvarDOS/edrdos/issues/75

**Comment by boeckmann** [comment]
Thanks for testing! That was on my list of things to be tested, because I thought this test case might fail.

**Comment by boeckmann** [comment]
A fix is pending with [64186cf](https://github.com/SvarDOS/edrdos/commit/64186cf539a6ca4f973d960364619fe909877996).

**Comment by ecm-pushbx** [comment]
It is a little magic because we assume that the Build BPB command actually points into a drbio UPB but there is no other easy way to get the int 13h unit from the block device.

**Comment by boeckmann** [comment]
@ecm-pushbx wouldn't init_runit be used instead introducing a new variable? Searching for init_runit, it is only set once.

**Comment by boeckmann** [comment]
Ok is see different segment. They really should have choosen different segment names :/

**Comment by ecm-pushbx** [comment]
Yeah I tried that at first but the segments got me. So I added the new variable. Hope I didn't mix up any of the segments!

**Comment by ecm-pushbx** [comment]
@boeckmann Will you pick my last changeset? I know the magic isn't good but usually the device will be our block device in which case it works. (I rushed to get it finished yesterday so it's still 2024 July.)

**Comment by boeckmann** [comment]
Yes I will. Have not as much time as the last two weeks though (holidays over). I will try to import it in the next days.

We should try to somehow document what all the segments are for, and when segments are accessible via DS and when not. Not quite sure whats the best way of documenting this.

**Comment by boeckmann** [comment]
> @boeckmann Will you pick my last changeset? I know the magic isn't good but usually the device will be our block device in which case it works. (I rushed to get it finished yesterday so it's still 2024 July.)

imported via 98653f619b0d62ba54b4c7dc0f8f41a47889570b
