### ISSUE TITLE
no int 24h when reading from an unformatted floppy

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/edrdos#90]
how to reproduce:

`dd if=/dev/zero of=floppyb.img bs=1024 count=1440`
`qemu-system-i386 -fda floppy.img -fdb floppy_b.img -vga cirrus -m 4M -cpu 486 -machine isapc -no-hpet`

result:

![image](https://github.com/user-attachments/assets/69a2d8a6-0fce-4348-8e04-c1438bfe0a6d)

expected: int 24h should have been called. this works with an unformatted partition, but not with an unformatted (all-zeroed) diskette.

**Comment by mateuszviste** [comment]
when accessing an unformatted partition then DR-DOS calls int 24h all right, and sets error 7 "Unknown disk media type" (tested with VBox):

![image](https://github.com/user-attachments/assets/e985bd45-bebe-4fdc-9c60-8e0c7a420958)

**Comment by mateuszviste** [comment]
SvarCOM with an int 24 handler that always panics with a "CRITICAL ERROR" message: 
[SvarCOM 2024.4 beta 3.zip](https://github.com/user-attachments/files/16588130/SvarCOM.2024.4.beta.3.zip)

**Comment by boeckmann** [comment]
> expected: int 24h should have been called. this works with an unformatted partition, but not with an unformatted (all-zeroed) diskette.

I only implemented it for fixed disks under the assumption that DR-DOS already provides a means to block access on unformatted removable media. As this is not the case according to your findings I have to investigate how this can be blocked.

**Comment by rofl0r** [comment]
forcing a reboot after accessing non-formatted media seems like the worst possible way to deal with this...

**Comment by mateuszviste** [comment]
> forcing a reboot after accessing non-formatted media seems like the worst possible way to deal with this...

The int 24h handler is a work in progress thing. The scope of this bug report is only to report an apparent misbehavior of the EDR kernel.

**Comment by boeckmann** [comment]
@mateuszviste does [b87fc26](https://github.com/SvarDOS/edrdos/commit/b87fc2630c169e7c50390b1c6cb11bab42e02abb) work for you?

**Comment by mateuszviste** [comment]
tested the (slightly more recent) d02e030 and...
![image](https://github.com/user-attachments/assets/b2e2bc83-e455-4d7f-90ae-31be7be63d03)

Seems good. :-)

**Comment by mateuszviste** [comment]
the returned error code is "general failure" (12). not sure it is the most appropriate for the situation, but that's a minor detail.

![image](https://github.com/user-attachments/assets/37b040fd-379c-49d1-80d7-972e679861d8)

**Comment by mateuszviste** [comment]
Oops, please my last two comments about the error code, it was actually a bad hack in my own code. With a proper interpreter it's all perfect. :-) I think this can be closed.

![image](https://github.com/user-attachments/assets/b5c99df8-2a67-4076-b3f0-dafb6669aa50)

**Comment by boeckmann** [comment]
There were still some flows in the code. UNSURE flag had to be set to make the kernel keep trying to login the drive after a failed attempt. I also made a differentiation between general io errors (disk not inserted etc.) and media type errors. I hope it is ok since [2053b4c](https://github.com/SvarDOS/edrdos/commit/2053b4cabdab292d54d2a2511ed44a511415a2c8)

**Comment by mateuszviste** [comment]
> I hope it is ok since [2053b4c](https://github.com/SvarDOS/edrdos/commit/2053b4cabdab292d54d2a2511ed44a511415a2c8)

I confirm it's still good for me. BTW are you planning some "formal" release of the kernel, or should I just occasionally grab the latest version from the github build?

**Comment by boeckmann** [comment]
I have not thought about it yet. We could probably declare some versions "good" from time to time, make a github release from them, and import them into svardos. Not sure if a more sophisticated versioning scheme than the "date is version" is needed. We could also follow the trend and count the releases, starting with release 1, with everything else not having a version, but only a git revision and build date.

**Comment by mateuszviste** [comment]
I think the "date is version" scheme is good, easy and unambiguous. I am more worried about which version I should pick for importing to SvarDOS. I would prefer to avoid versions where you possibly have some "work in progress" things pending and such. Maybe you could flag a version from time to time as "assumed to be production compatible"? Or better, if you just copy the github-built svp into the SvarDOS repo based on your knowledge of which version is most likely to be good that would be perfect. :-)

**Comment by boeckmann** [comment]
Yes I can do that. I would start with the current git revision. It should be "better" than the current one. There still is https://github.com/SvarDOS/edrdos/issues/87, but this is also in the current package version.

**Comment by mateuszviste** [comment]
Interestingly, the "unformatted floppy" test also works with FreeDOS. Meaning that the kernel does not call the int 24h handler when seeing a 1.44M totally zeroed floppy and displays it as empty, even providing a serial number and the correct amount of free space. It's also able to write a file to it, all seemingly working fine.

![image](https://github.com/user-attachments/assets/f8570ed6-b2f8-4319-91a7-b3ef9168e60f)

This same diskette (with the test file on it) is unreadable under EDR.
MS-DOS 5.0 and 6.0 are also unable to read this diskette, so I guess we can call this a FreeDOS misfeature.
