### ISSUE TITLE
HIGHSHELL is not a FreeDOS fdconfig.sys directive

### ISSUE THREAD

**Issue by ecm-pushbx** [SvarDOS/edrdos#91]
You added a "HIGHSHELL" directive in https://github.com/SvarDOS/edrdos/commit/a3d543b6315e8400a2635e6a20a351d996a31835

This does not match FreeDOS which recognises SHELLHIGH: https://github.com/FDOS/kernel/blob/f7947771cb5ca99ddf76b2c1ea07ce54f70dfb5c/kernel/config.c#L294

Further, it also doesn't match the style of DR-DOS dconfig.sys directives with a high prefix because then it should read "HISHELL".

**Comment by boeckmann** [comment]
fixed.
