### ISSUE TITLE
Init environment too large?

### ISSUE THREAD

**Issue by ecm-pushbx** [SvarDOS/edrdos#92]
In this commit: https://github.com/SvarDOS/edrdos/commit/f9bad8d85fb7a56d6062eb978f963022fd51863c#diff-52bbf87db189a4af9f24037eb12b3b9563a54bfc343b81073ad25c86fbf9f5dcL4043

You state:

```
					; >>> end of range copied to seg 60
					;     may not exceed 256 bytes
```

However, I am counting 251 + 2 + 1 + 2 + 1 bytes, which is 257 bytes.

**Comment by boeckmann** [comment]
fixed. Sometimes it helps if one can count.

**Comment by ecm-pushbx** [comment]
As you know, the two great problems in program logic work are naming things, cache invalidation, and off-by-one errors =)

**Comment by boeckmann** [comment]
We shell leave this open to amuse the people who drive by...
