### ISSUE TITLE
Drive letter ordering slightly confusing when more than one hdd

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/edrdos#94]
It is nice that EDR is not influenced by the ACTIVE flag of partitions when ordering letters, because no matter which partition it boots from, the drive letters are still the same.

It is not so nice however if 2 disks are present. On both disks I have created a single partition. Installed SvarDOS on the secondary disk. The primary disk is empty. When system boots, it assign the C: letter to my secondary disk, and D: to the primary.

The "issue" is when I boot from a floppy. Then, suddenly, letters are inverted. Same would happen of course if I had a system on both drive - then whichever boots would "steal" the C: letter.

I understand the reason, besides MS-DOS does the same. Just wanted to ask - is it what we want? Wouldn't it be more logical to order disks always in the same way, following the spirit of "active flag partition does not change drive letter ordering"?

**Comment by mateuszviste** [comment]
background reason of this issue: when the SvarDOS installer installs the system, it does not know what letter will be assigned to the system drive once it will boot from it.

**Comment by boeckmann** [comment]
Sure this is not a BIOS thing? it might re-order the disks if booted from the second drive, so physical drive 80h becomes 81h and 81 becomes 80h?

**Comment by mateuszviste** [comment]
Might be indeed. And even if not, then it is not impossible that some BIOS implementation out there does this, so relying on drive letters when booted from the floppy is probably not a good idea anyway. I will change the SvarDOS installation process so it is resilient to drive letter changes between reboots.
