### ISSUE TITLE
BUFFERSHIGH yields an error message "Invalid number of buffers"

### ISSUE THREAD

**Issue by mateuszviste** [SvarDOS/edrdos#95]
Adding `BUFFERSHIGH=8` in CONFIG.SYS makes the EDR kernel display the message `Invalid number of buffers` at boot.
I tried different values (2, 4, 8, 16, 24..), same result.
The same CONFIG.SYS works with FreeDOS (or at least - no error message is displayed).

Changing "BUFFERSHIGH=8" to "BUFFERS=8" makes the error message go away.

Maybe the message means that the number of buffers will not fit into HMA (or is it UMB?), but if so then it should probably be worded differently.

**Comment by boeckmann** [comment]
I think there is only a HIBUFFERS command, no BUFFERSHIGH.

**Comment by mateuszviste** [comment]
> I think there is only a HIBUFFERS command, no BUFFERSHIGH.

Then the error message is still misleading, as it suggests the command is somewhat understood but failed to be applied (talks specifically about "buffers"). Bad parsing?

**Comment by mateuszviste** [comment]
bad (lazy) parsing bug confirmed:

![image](https://github.com/user-attachments/assets/e7dfb848-5682-41a7-b191-5472b0612c34)

**Comment by boeckmann** [comment]
yes lazy parsing. it finds BUFFERS as a command end then tries to skip spaces (none there) and tests for = or ?. But it does not complain, because the = is optional. it then tries to parse the rest of the line as a number.

**Comment by boeckmann** [comment]
`scan` is the subroutine that deals with it:
https://github.com/SvarDOS/edrdos/blob/83b66305d6498cad55c585ede6a6a639cbc3fdc1/drbio/genercfg.asm#L2681-L2722

**Comment by mateuszviste** [comment]
maybe an easy compromise would be to register BUFFERSHIGH as an alias to BUFFERS? BUFFERSHIGH is a valid MSDOS directive and it is also supported by FreeDOS, hence it is possible some users migrating from the FreeDOS kernels would have it in CONFIG.SYS (was my case).

**Comment by boeckmann** [comment]
Ok, will implement it.

**Comment by boeckmann** [comment]
Should be fixed by https://github.com/SvarDOS/edrdos/commit/8b1c69ca12c500af2e54dda6d94e242a3da2abf3

**Comment by mateuszviste** [comment]
I confirm - no more error message. Thank you! :) (closing the issue)

A question, if you don't mind: with `BUFFERS=10` (or `BUFFERSHIGH=10`, does not matter), the kernel shows a message about "1 in TPA":

![image](https://github.com/user-attachments/assets/b9ae5fcd-807b-4b24-8b30-845c926c6851)

It's two questions, actually:
1. What is "TPA" ?
2. Why does it says it allocated "1", while I asked for 10? (message is the same also for 20 or 50)

**Comment by boeckmann** [comment]
TPA stands for "transient program area". It is basically the memory available for DOS programs below the BIOS region or end of memory, whatever comes first. So typically the memory below 640K. Are you sure this message comes from the kernel? I did not find this message in the kernel source.

**Comment by boeckmann** [comment]
No problem. Could have been my question :D
