### ISSUE TITLE
readme file is outdated (JWasm, uncompressed single-file SvarDOS flavour)

### ISSUE THREAD

**Issue by ecm-pushbx** [SvarDOS/edrdos#98]
Here it is stated that the jwasmr executable would be used, which I believe you changed recently: https://github.com/SvarDOS/edrdos/blob/8b1c69ca12c500af2e54dda6d94e242a3da2abf3/README.md?plain=1#L34

Here it is stated that the single-file SvarDOS flavour kernel when not compressed must be loaded to segment 70h, which I also think you changed since: https://github.com/SvarDOS/edrdos/blob/8b1c69ca12c500af2e54dda6d94e242a3da2abf3/README.md?plain=1#L60

**Comment by ecm-pushbx** [comment]
In this part you also mentioned that the not compressed single-file kernel needs the EDR-DOS load protocol: https://github.com/SvarDOS/edrdos/blob/8b1c69ca12c500af2e54dda6d94e242a3da2abf3/README.md?plain=1#L97

**Comment by ecm-pushbx** [comment]
In this part you list "GNU public license" and link to the COPYING file: https://github.com/SvarDOS/edrdos/blob/8b1c69ca12c500af2e54dda6d94e242a3da2abf3/README.md?plain=1#L104

To be more accurate you should change this to refer to "the GNU General Public License, v2 or any later version". The more appropriate link is https://github.com/FDOS/kernel/blob/c0127001908405d30d90f1755ad10c1b59ea8c90/sys/sys.c#L14 because that includes the crucial wording about the allowed versions. Dropping a COPYING file into a project may suffice to indicate the current version but the GNU GPL specifically states that the applicable version upgrade options depend on the exacting wording in the source text files.

**Comment by boeckmann** [comment]
Yes I have not touched this for some time. Will update it today afternoon...

**Comment by ecm-pushbx** [comment]
You updated the version information in https://github.com/SvarDOS/edrdos/commit/30602140763750af65c5af0ca8e38c5754a97817#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R136 but it still says "GNU public license". This is inaccurate.

**Comment by ecm-pushbx** [comment]
In https://github.com/SvarDOS/edrdos/commit/30602140763750af65c5af0ca8e38c5754a97817#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R115 you misspelled "protocol". Also, I am confused, does this mean the dual-file drbio.sys can be used with the FreeDOS load protocol? That'd be news to me.

**Comment by boeckmann** [comment]
> In [3060214#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R115](https://github.com/SvarDOS/edrdos/commit/30602140763750af65c5af0ca8e38c5754a97817#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R115) you misspelled "protocol". Also, I am confused, does this mean the dual-file drbio.sys can be used with the FreeDOS load protocol? That'd be news to me.

Thanks for the hint. Yes, it can be used with the FreeDOS protocol if renamed to kernel.sys.

**Comment by boeckmann** [comment]
But of course DRDOS.SYS must also exist, otherwise you do not have a complete kernel :)

**Comment by ecm-pushbx** [comment]
> But of course DRDOS.SYS must also exist, otherwise you do not have a complete kernel :)

Yes, that much is understood.

**Comment by ecm-pushbx** [comment]
> > In [3060214#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R115](https://github.com/SvarDOS/edrdos/commit/30602140763750af65c5af0ca8e38c5754a97817#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R115) you misspelled "protocol". Also, I am confused, does this mean the dual-file drbio.sys can be used with the FreeDOS load protocol? That'd be news to me.
> 
> Thanks for the hint. Yes, it can be used with the FreeDOS protocol if renamed to kernel.sys.

Thanks, I verified this. During testing I came up with https://github.com/SvarDOS/edrdos/issues/100 (wow, number 100!)

**Comment by boeckmann** [comment]
> You updated the version information in [3060214#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R136](https://github.com/SvarDOS/edrdos/commit/30602140763750af65c5af0ca8e38c5754a97817#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R136) but it still says "GNU public license". This is inaccurate.

I added your proposed text?!? Albeit outside the link...

**Comment by ecm-pushbx** [comment]
> > You updated the version information in [3060214#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R136](https://github.com/SvarDOS/edrdos/commit/30602140763750af65c5af0ca8e38c5754a97817#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R136) but it still says "GNU public license". This is inaccurate.
> 
> I added your proposed text?!? Albeit outside the link...

You added a clause reading ", v2 or any later version.". No problems with that, but the proper name of the license is GNU General Public License, not "GNU public license".

**Comment by boeckmann** [comment]
Ah, that was the mistake :)
